### PR TITLE
Implemented a rule on only one remove per turn

### PR DESCRIPTION
**Pull request by hanzemeng**

### CODE REVIEW

**Comment by neilbalch** [comment]
Wait, I don't follow what was wrong with the previous version of the code. Was it not changing the turn after a successful move?

**Comment by hanzemeng** [comment]
> Wait, I don't follow what was wrong with the previous version of the code. Was it not changing the turn after a successful move?

One can remove up to 3 balls per turn in the previous version; to prevent stalemate, there is a rule that limits number of remove per turn

**Comment by neilbalch** [comment]
But the turn is supposed to automatically switch no matter what after a successful move... Is that not working?

**Comment by hanzemeng** [comment]
> But the turn is supposed to automatically switch no matter what after a successful move... Is that not working?

One turn has 3 actions (the very first turn only has 2 actions); in each turn, only 1 action can be remove.

**Comment by hanzemeng** [comment]
Changing team is working properly

**Comment by neilbalch** [comment]
Oh lol I didn't realize that was a part of the rules.

**Review by neilbalch — APPROVED** [review]

**Pull request merged**
